ORG 00H
	MOV 60H, #0A5H
	MOV 61H, #0FDH
	MOV 62H, #067H
	MOV 63H, #042H
	MOV 64H, #0DFH
	MOV 65H, #09AH
	MOV 66H, #084H
	MOV 67H, #01BH
	MOV 68H, #0C7H
	MOV 69H, #031H

	MOV R6,#60H      
	MOV R7,#10
	ACALL ASC_SORT
	ACALL DELAY
	MOV R6,#60H
	MOV R7,#10
	ACALL DESC_SORT
	SJMP $

ASC_SORT:
;SORT NUMBERS AT ADDRESS GIVEN BY R6 IN ASCENDING ORDER USING BUBBLE SORT
;R7 IS COUNT
	DEC R7
	MOV 03H,07H          
	NEXTI: MOV 02H,07H   
	MOV 00H,06H          
NEXTN: MOV A,@R0
	INC R0
	MOV B,@R0
	CLR C
	SUBB A,B
	MOV 0H,C
	ADD A,B
	JB 0H,SMALLER          ;ALREADY IN ORDER              
	;SWAPPING CONTENTS WHEN NOT IN ORDER
	XCH A,@R0
	DEC R0
	MOV @R0,A
	INC R0
SMALLER: DJNZ R2,NEXTN
	;INC R6                 ;LOWER ADDRESS IS SORTED
	DEC R7                 ;ONE MORE NUMBER IS SORTED
	DJNZ R3, NEXTI
	RET

DESC_SORT:
;SORT NUMBERS AT ADDRESS GIVEN BY R6 IN DESCENDING ORDER USING SELECTION SORT,
;R7 HAS COUNT
;CHANGES R7,R6,R3,R2,R1,R0,A,B
	MOV 03H,07H           
NEXTIT: MOV 02H,07H    
	MOV 00H,06H           
	MOV A,@R0
	MOV 01H,00H           
NEXTNU: INC R0
	MOV B,@R0
	CLR C
	SUBB A,B
	MOV 0H,C
	ADD A,B
	JNB 0H,LARGER         ;ALREADY IN ORDER
	MOV 01H,00H           
	XCH A,B               ;NEW LARGER NUMBER
LARGER: DJNZ R2,NEXTNU
	MOV 00H,06H           ;MOV R0,R6
	MOV A,@R1
	XCH A,@R0
	MOV @R1,A
	INC R6                ;LOWER ADDRESS IS SORTED
	DEC R7                ;ONE MORE NUMBER IS SORTED
	DJNZ R3, NEXTIT
	RET
DELAY: MOV R6,#0FFH
OUTLOOP: MOV R7,#0FFH
INLOOP: DJNZ R7,INLOOP
	DJNZ R6,OUTLOOP
	RET
END