ORG 00
	MOV B,#00H    
	MOV R7,#20H   
	MOV R0,#40H  

;STORING LIST OF NUMBERS
	INC R7
	MOV R2,#0        ;COUNT OF NUMBERS
NEXT: MOV @R0,A
	INC A
	INC R0
	INC R2
	CLR C
	SUBB A,R7
	MOV 0H,C
	ADD A,R7
	JB 0H,NEXT

	MOV R0,#40H  ;POINTER TO LIST OF NUMBERS
	MOV R1,#61H  ;LIST OF EXTRACTED PRIMES
	CALL EXTRACT_PRIME
	SJMP $

EXTRACT_PRIME:
;R0 POINTS TO LIST OF NUMBERS
;R2 CONTAINS SIZE OF LIST
;R1 POINTS TO LOCATION WHERE TO STORE PRIMES
NEXT_NUM: MOV A,@R0
	CALL IS_PRIME
	JNB 0H,NOT_A_PRIME
	MOV A,@R0
	MOV @R1,A
	INC R1
NOT_A_PRIME: INC R0
	DJNZ R2,NEXT_NUM
	RET

IS_PRIME:
	MOV R4,A
	CLR C
	RRC A              ;A = A/2
	MOV R3,A          ;MAXIMUM NUMBER UP TO WHICH TO CHECK FOR FACTOR
	JZ NOT_PRIME   ;IF A IS 0 OR 1 THEN NOT PRIME
	DEC R3
	MOV A,R3
	JZ PRIME   ;IF A IS 2 OR 3 THEN PRIME
NEXTI: INC R3
	MOV A,R4
	MOV B,R3
	DIV AB
	MOV A,B
	JZ NOT_PRIME
	DEC R3
	DJNZ R3,NEXTI
PRIME: SETB 0H
	SJMP FIN
NOT_PRIME: CLR 0H
FIN: RET

END